# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
build_checkerboard_weights <- function(X, Y, resolution) {
    .Call(`_qad_build_checkerboard_weights`, X, Y, resolution)
}

#' @export
local_kernel_integral <- function(A, x, y, N, y_sum) {
    .Call(`_qad_local_kernel_integral`, A, x, y, N, y_sum)
}

#' @export
D1_Pi <- function(A, resolution) {
    .Call(`_qad_D1_Pi`, A, resolution)
}

